organisms = [''] + sorted([
    'Ascaris lumbricoides',
    'Fasciolopsis',
    'Opisthorchis spp.',
    'Plasmodium spp.',
    'Plasmodium vivax',
    'Plasmodium malariae',
    'Plasmodium falciparum',
    'Plasmodium ovale',
    'Strongyloides stercolaris',
    'Taenia spp.',
    'Trichuris trichiura',
    'Hookworm',
    'Hymenolepis nana',
    'Hymenolepis diminuta',
    'Entamoeba coli',
    'Entamoeba histolytica',
    'Endolimax nana',
    'Blastocystis hominis',
    'Artifact',
    'Giardia lamblia',
    'Yeast',
    'Iodamoeba butschlii',
])

stages = [''] + sorted([
    '-',
    'adult',
    'cyst',
    'egg',
    'ring form',
    'gametocyte',
    'growing trophozoite',
    'growing trophozoite (band form)',
    'rhabditiform larvae',
    'filariform larvae',
    'larvae',
    'merozoite',
    'schizont',
    'vacuolar form',
    'sexual form',
    'asexual form',
    'embryonated egg',
    'unfertilized egg',
    'decorticated egg',
    'fertilized egg',
    'pre-cyst'

])